### ISSUE TITLE
 CCurlFile::Stat - Failed: HTTP response code said error(22)

### ISSUE THREAD

**Issue by undead-osiris** [bromix/plugin.audio.soundcloud#21]
hello
got the error (Raspberry pi 2, Linux xbian 3.18.8+ #1 SMP PREEMPT Mon Mar 2 03:14:40 CET 2015 armv7l GNU/Linux)

21:47:46 T:1758458896  NOTICE: [plugin.audio.soundcloud] Running: SoundCloud (1.1.2~beta2) on Helix (2.19) with Python 2.7.3
21:47:47 T:1960325120   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for https://cf-media.sndcdn.com/WaKcXaIk9dVO.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLW1lZGl
hLnNuZGNkbi5jb20vV2FLY1hhSWs5ZFZPLjEyOC5tcDMiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE0MjU0OTUyMDV9fX1dfQ__&Signature=I2DajcF44h5GwUmiGRhXeYEEJiCRkvxMtN6XaWXR0CNtlSsD3GeyCLzRMmPYuq
bOmn~UxZ63Hl1189KagS-tAzDE7V7cCVEGVpldn3RHH7q80wEUzxzfy8luVAWzyiWfginKaCr4OHQCWSlxwWIHtA-5cJEoBnjmac3vT3xe9UF0fdJMrKbnq44ayzrityTrPVVk3DLeZoapbEYxXsAj2vMAW878EZEAXhBKF9VfJFopexU5H~-~A2kQP23n59uYTdO2~Mzw
9R3EdF0g~Ml~MC8Agd0BtCNkO7PSSKeyABdMOnGm0Jc5a2LrZjRWj4InCj0J18Mf-Vu0teJmYmM6aA__&Key-Pair-Id=APKAJAGZ7VMH2PFFW6UQ
21:47:48 T:1960325120   ERROR: Previous line repeats 1 times.
21:47:48 T:1960325120   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 0
21:47:48 T:1960325120  NOTICE: CCurlFile::FillBuffer - Reconnect, (re)try 1

**Comment by bromix** [comment]
Please contact someone of xbian...this is not an issue of the addon. xbian is missing some dependencies (like https support in curl, also xbian has problems with libciel 3.40)
