### ISSUE TITLE
invalid client

### ISSUE THREAD

**Issue by firsttris** [bromix/plugin.audio.soundcloud#31]
hello bromix,

soundcloud plugin says "invalid client" and refuses to login.

09:22:14 1950.329102 T:1727788032    INFO: CPythonInvoker(16, /storage/.kodi/addons/plugin.audio.soundcloud/addon.py): script successfully run
09:22:14 1950.344116 T:1727788032    INFO: Python script stopped
09:22:14 1950.344482 T:1727788032   DEBUG: Thread LanguageInvoker 1727788032 terminating
09:22:14 1950.379517 T:1967063040   DEBUG:  WaitOnScriptResult - plugin exited prematurely - terminating
09:22:14 1950.380005 T:1967063040   ERROR: GetDirectory - Error getting plugin://plugin.audio.soundcloud/
09:22:14 1950.380371 T:1967063040   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.soundcloud/) failed
09:22:14 1950.380493 T:1967063040   DEBUG: CGUIMediaWindow::GetDirectory ()
09:22:14 1950.380615 T:1967063040   DEBUG:   ParentPath = [plugin://plugin.audio.soundcloud/]

regards
Tristan

**Comment by bromix** [comment]
Please provide a complete debug log via pastebin.com or similar. I've to know to system and python version.

**Comment by firsttris** [comment]
Hey bromix,

everything was working fine till i changed password in soundcloud, now i unable to login from you kodi addon.

here is the debug log:
http://pastebin.com/8jjTAuRn

regards
tristan

**Comment by bromix** [comment]
Have you changed the password in the addon?

**Comment by bromix** [comment]
Your log is still incomplete. Provide a debug log after the failed login.

**Comment by firsttris** [comment]
the debug log was created during the failed login. 

heres another one:

http://pastebin.com/c1EQTcA6

**Comment by bromix** [comment]
Do you have the same problem with Isengard (Kodi 15.X)

I tested my login with special and normal characters and all works fine.

**Comment by firsttris** [comment]
Holla,

i have tested on Kodi 15.1 (Isengard) Openelec 5.95.5 on my rpi2
and 
Desktop PC -  Kodi 15.1 (Isengard)

on both systems (clean install): i get invalid_client as notification in kodi when trying to log in.

I think getting the Access token fails somehow...

what i did: use addon version 2.0.0 to get a access token and go back to 2.0.2

**Comment by bajo** [comment]
@firsttris thank you for the hint to use 2.0.0 for the first login. With this I could login and update to 2.0.2 where the addon still works. 
Tested on OpenELEC 5.95.2 imx6.arm (Cubox i4-pro)
